NAME	= megaphone
	
CC		= c++
CFLAGS	= -Wall -Wextra -Werror -std=c++98
RM		= rm -rf

#Colors:
GREEN		=	\e[92;5;118m
YELLOW		=	\e[93;5;226m
GRAY		=	\e[33;2;37m
RESET		=	\e[0m
CURSIVE		=	\e[33;3m

all: $(NAME)

$(NAME): 
	printf "$(CURSIVE)$(GRAY) 	- Compiling $(NAME)... $(RESET)\n"
	$(CC) $(CFLAGS) megaphone.cpp -o $(NAME)
	printf "$(GREEN)    - Executable ready.\n$(RESET)"

clean:
	$(RM) $(NAME)
	printf "$(YELLOW)    - Executable removed.$(RESET)\n"

fclean:
	clean

re: clean all

.PHONY: all clean re fclean
.SILENT: clean fclean all $(NAME)